# Generated by Django 5.1.6 on 2025-02-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
