# Generated by Django 5.1.6 on 2025-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
