# Generated by Django 5.1.6 on 2025-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
