# Generated by Django 5.1.6 on 2025-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_item_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
