# Generated by Django 5.1.6 on 2025-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro')], default='usd', max_length=3),
        ),
    ]
